pipeline {
    agent any
 
    stages {
        stage('Test') {
            steps {
 
                // To run Maven on a Windows agent, use
                dir('bddframework'){
                bat 'mvn verify -Dbrowser=Chrome -DsiteUrl=https://www.booking.com/ -DtimeOut=15 -DtimeOutInMillis=200 -Dcucumber.filter.tags="@Regression"'
                }
            }
 
            post {
                 
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the jar file.
                always {
                        cucumber buildStatus: 'null', 
                        customCssFiles: '', 
                        customJsFiles: '', 
                        failedFeaturesNumber: -1, 
                        failedScenariosNumber: -1, 
                        failedStepsNumber: -1, 
                        fileIncludePattern: '**/*.json', 
                        pendingStepsNumber: -1, 
                        skippedStepsNumber: -1, 
                        sortingMethod: 'ALPHABETICAL', 
                        undefinedStepsNumber: -1

                        dir('bddframework'){
                        bat 'mvn exec:java -D"exec.mainClass"="Utilities.SendEmail" -DemailHost=smtp.gmail.com -DemailPort=587 -DtoEmail=palekarvivek6@gmail.com -DemailApp="zmdw whoh jsal tqvp" -DfromEmail=nikki17rajurkar@gmail.com -DemailPDF=/target/PDFReport/ExtentPdf.pdf'    
                    }
                }
            }
        }
  }
}